//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Balashova_YP_9.ApplicationData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ObshestvoEntities : DbContext
    {
        private static ObshestvoEntities _context;
        public static ObshestvoEntities GetContext()
        {
            if (_context == null)
                _context = new ObshestvoEntities();
            return _context;
        }
        public ObshestvoEntities()
            : base("name=ObshestvoEntities")
        {
        }
        
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RegistraciaClienta> RegistraciaClienta { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Vrachi> Vrachi { get; set; }
        public virtual DbSet<ZapisNaPriem> ZapisNaPriem { get; set; }
    }
}
